### ISSUE TITLE
Create h2inc class

### ISSUE THREAD

**Issue by Lerking** [Lerking/h2inc#1]
Class must contain basic functions for file I/O.
- [x] Traverse functions from task #2
- [x] Read function from task #3 
- [x] Write function from task #4

**Comment by Lerking** [comment]
Added traverse functions srcfilecnt and srcfoldercnt.
Added read_file function.
Added write_file function.
